// <auto-generated />
using System;
using CoffeeBeans.backend.Web.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeBeans.backend.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoffeeBeans.backend.Web.Domain.BeanAggregate.Bean", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<double>("BagWeightG")
                        .HasColumnType("double");

                    b.Property<int>("NumAcidityNotes")
                        .HasColumnType("int");

                    b.Property<int>("NumFarms")
                        .HasColumnType("int");

                    b.Property<int>("NumSweetnessNotes")
                        .HasColumnType("int");

                    b.Property<double>("RoastIndex")
                        .HasColumnType("double");

                    b.Property<string>("TastingProfile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<double>("X")
                        .HasColumnType("double");

                    b.Property<double>("Y")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Beans", (string)null);
                });

            modelBuilder.Entity("CoffeeBeans.backend.Web.Domain.BeanAggregate.BeanCustomValue", b =>
                {
                    b.Property<Guid>("BeanId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomColumnId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("BeanId", "CustomColumnId");

                    b.HasIndex("CustomColumnId");

                    b.ToTable("BeanCustomValues", (string)null);
                });

            modelBuilder.Entity("CoffeeBeans.backend.Web.Domain.BeanAggregate.CustomColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CustomColumns", (string)null);
                });

            modelBuilder.Entity("CoffeeBeans.backend.Web.Domain.BeanAggregate.BeanCustomValue", b =>
                {
                    b.HasOne("CoffeeBeans.backend.Web.Domain.BeanAggregate.Bean", "Bean")
                        .WithMany("CustomValues")
                        .HasForeignKey("BeanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeBeans.backend.Web.Domain.BeanAggregate.CustomColumn", "CustomColumn")
                        .WithMany("CustomValues")
                        .HasForeignKey("CustomColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bean");

                    b.Navigation("CustomColumn");
                });

            modelBuilder.Entity("CoffeeBeans.backend.Web.Domain.BeanAggregate.Bean", b =>
                {
                    b.Navigation("CustomValues");
                });

            modelBuilder.Entity("CoffeeBeans.backend.Web.Domain.BeanAggregate.CustomColumn", b =>
                {
                    b.Navigation("CustomValues");
                });
#pragma warning restore 612, 618
        }
    }
}
